language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    env: PYTHON_VERSION=3.7 CPP=14 COMPILER=gcc-7 SONAR=true
    name: Python 3.7, c++14, gcc 7 Sonar
    addons:
      apt:
        sources:
          - deadsnakes
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - python3.7-dev
          - python3.7-venv

env:
  global:
    - DEBUG_CI=true
    
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.local/lib
  - $HOME/.local/include
  - $HOME/Library/Python

install:
  # Install dependencies
  - |
    #!/usr/bin/env bash
    set -e
    [[ "$DEBUG_CI" == true ]] && set -x
    . ${TRAVIS_BUILD_DIR}/.travis-ci/load_env.sh
    ${TRAVIS_BUILD_DIR}/.travis-ci/install.sh
    ${TRAVIS_BUILD_DIR}/.travis-ci/install_sonar.sh; fi

before_script:
  # report found build tools
  - ${TRAVIS_BUILD_DIR}/.travis-ci/before_script.sh

script:
  - |
    #!/usr/bin/env bash
    set -e
    [[ "$DEBUG_CI" == true ]] && set -x
    ${TRAVIS_BUILD_DIR}/.travis-ci/sonar_analysis.sh

after_failure: 
  - cat tests/test_cmake_build/*.log*
