name: Bug MRE

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  build:
    name: ${{ matrix.config.name }}
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        carma_version : ["stable", "unstable"]
        config: 
        - {
            name: "Windows (MSVC)",
            os: windows-latest,
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            generators: "Visual Studio 17 2022",
            target: "ALL_BUILD"
          }
        - {
            name: "Windows (Clang)",
            os: windows-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang",
            generators: "Ninja",
            target: "ALL_BUILD"
          }
        - {
            name: "Ubuntu (Clang-10)",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-10",
            cxx: "clang++-10",
            generators: "Ninja",
            target: "all"
          }
        - {
            name: "Ubuntu (Clang-11)",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-11",
            cxx: "clang++-11",
            generators: "Ninja",
            target: "all"
          }
        - {
            name: "Ubuntu (GCC-9)",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-9",
            cxx: "g++-9",
            generators: "Ninja",
            target: "all"
          }
        - {
            name: "macOS (Clang)",
            os: macos-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja",
            target: "all"
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install cmake
          ninja --version
          cmake --version

      - name: Set up Clang (Windows)
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install dependencies on ubuntu
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade cmake
          ninja --version
          cmake --version

      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          python -m pip install cmake
          ninja --version
          cmake --version
      
      - name: Install python pacakges
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install numpy pytest
          
      - name: Configure
        run: |
          cd mre
          export PY_CMD=$(python -c 'import sys; print(sys.executable)')

          cmake \
            -DUSE_CARMA_VERSION=${{ matrix.carma_version }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_INSTALL_PREFIX:PATH=. \
            -DPython3_EXECUTABLE=${PY_CMD} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generators }}" \
            -B build -S .

      - name: Build
        run: |
            cd mre
            cmake \
              --build build \
              --target install \
              --config ${{ matrix.config.build_type }}

      - name: Test
        run: |
          cd mre
          python -m pytest -v pymod_test.py
