name: Test Numpy versions
on: 
  push:
    branches:
      - stable
      - unstable
  pull_request:
    branches:
      - stable
      - unstable
  schedule:
    - cron: '0 14 * * 1'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Minimum Numpy version",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-9",
            cxx: "g++-9",
            generators: "Ninja",
            target: "all",
            numpy: "numpy==1.14.6"
          }
        - {
            name: "Latest Numpy version",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-9",
            cxx: "g++-9",
            generators: "Ninja",
            target: "all",
            numpy: "numpy>1.14.6"
          }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest cmake
          python -m pip install ${{ matrix.config.numpy }}
          sudo apt install \
            libxcursor-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxi-dev \
            libglew-dev \
            libopenblas-dev
          ninja --version
          cmake --version

      - name: Configure
        run: |
          mkdir build
          cd build

          export PY_CMD=$(python -c 'import sys; print(sys.executable)')

          cmake \
            -DBUILD_TESTS=ON \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_INSTALL_PREFIX:PATH=. \
            -DPython3_EXECUTABLE=${PY_CMD} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "Ninja" \
            ..

      - name: Build
        run: |
            cd build
            cmake \
              --build . \
              --target ${{ matrix.config.target }} \
              --config ${{ matrix.config.build_type }}

      - name: Test
        run: |
            cd build
            ctest \
              -C ${{ matrix.config.build_type }} \
              -V --rerun-failed --output-on-failure
